<?php

class ActivityTableSeeder extends Seeder {

    public function run()
    {
        DB::table('activities')->delete();

         Activity::create([
            'activityName'      => 'Activité 1',
            'activityDesc' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit facilis hic tenetur sapiente aliquam. Minima quod a rem voluptas soluta commodi libero laudantium illo, exercitationem aspernatur blanditiis beatae saepe hic excepturi nihil doloribus rerum eum sequi molestias cupiditate illum odio aliquam ratione sint. Dolore, harum quisquam cupiditate doloribus eius ullam, id perspiciatis. Placeat necessitatibus architecto nulla maiores eos eligendi vitae vero. Libero officiis sit cupiditate ratione mollitia qui, ullam, accusamus sequi repellendus impedit cumque amet eos ab nesciunt nihil quod vitae odit a. Repellendus consequatur ea quos ab eaque. Quibusdam sed voluptate omnis quam, est dicta consectetur soluta sunt, recusandae praesentium cumque mollitia explicabo quo dignissimos a porro consequuntur delectus quia repellendus saepe, deserunt, voluptatum adipisci esse non facere. Officia explicabo, nihil dolorum nemo necessitatibus libero omnis, velit magni numquam alias! Sequi quisquam ex excepturi nobis, laudantium ut reiciendis. Perspiciatis voluptas provident itaque quis odio quam, commodi quidem nam voluptate eveniet, esse nisi adipisci totam deserunt illum voluptatem eaque. Facilis maxime quia error soluta aliquid quasi aspernatur, enim, tempora nobis necessitatibus ea nemo voluptate deleniti eius. Harum aliquid ab voluptate voluptatibus ipsam. Incidunt facere odio, alias nisi error, adipisci totam rerum, sequi fuga nobis culpa quos voluptates hic atque consequatur.'
            ]);
         Activity::create([
            'activityName'      => 'Activité 2',
            'activityDesc' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit facilis hic tenetur sapiente aliquam. Minima quod a rem voluptas soluta commodi libero laudantium illo, exercitationem aspernatur blanditiis beatae saepe hic excepturi nihil doloribus rerum eum sequi molestias cupiditate illum odio aliquam ratione sint. Dolore, harum quisquam cupiditate doloribus eius ullam, id perspiciatis. Placeat necessitatibus architecto nulla maiores eos eligendi vitae vero. Libero officiis sit cupiditate ratione mollitia qui, ullam, accusamus sequi repellendus impedit cumque amet eos ab nesciunt nihil quod vitae odit a. Repellendus consequatur ea quos ab eaque. Quibusdam sed voluptate omnis quam, est dicta consectetur soluta sunt, recusandae praesentium cumque mollitia explicabo quo dignissimos a porro consequuntur delectus quia repellendus saepe, deserunt, voluptatum adipisci esse non facere. Officia explicabo, nihil dolorum nemo necessitatibus libero omnis, velit magni numquam alias! Sequi quisquam ex excepturi nobis, laudantium ut reiciendis. Perspiciatis voluptas provident itaque quis odio quam, commodi quidem nam voluptate eveniet, esse nisi adipisci totam deserunt illum voluptatem eaque. Facilis maxime quia error soluta aliquid quasi aspernatur, enim, tempora nobis necessitatibus ea nemo voluptate deleniti eius. Harum aliquid ab voluptate voluptatibus ipsam. Incidunt facere odio, alias nisi error, adipisci totam rerum, sequi fuga nobis culpa quos voluptates hic atque consequatur.'
            ]);
         Activity::create([
            'activityName'      => 'Activité 3',
            'activityDesc' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit facilis hic tenetur sapiente aliquam. Minima quod a rem voluptas soluta commodi libero laudantium illo, exercitationem aspernatur blanditiis beatae saepe hic excepturi nihil doloribus rerum eum sequi molestias cupiditate illum odio aliquam ratione sint. Dolore, harum quisquam cupiditate doloribus eius ullam, id perspiciatis. Placeat necessitatibus architecto nulla maiores eos eligendi vitae vero. Libero officiis sit cupiditate ratione mollitia qui, ullam, accusamus sequi repellendus impedit cumque amet eos ab nesciunt nihil quod vitae odit a. Repellendus consequatur ea quos ab eaque. Quibusdam sed voluptate omnis quam, est dicta consectetur soluta sunt, recusandae praesentium cumque mollitia explicabo quo dignissimos a porro consequuntur delectus quia repellendus saepe, deserunt, voluptatum adipisci esse non facere. Officia explicabo, nihil dolorum nemo necessitatibus libero omnis, velit magni numquam alias! Sequi quisquam ex excepturi nobis, laudantium ut reiciendis. Perspiciatis voluptas provident itaque quis odio quam, commodi quidem nam voluptate eveniet, esse nisi adipisci totam deserunt illum voluptatem eaque. Facilis maxime quia error soluta aliquid quasi aspernatur, enim, tempora nobis necessitatibus ea nemo voluptate deleniti eius. Harum aliquid ab voluptate voluptatibus ipsam. Incidunt facere odio, alias nisi error, adipisci totam rerum, sequi fuga nobis culpa quos voluptates hic atque consequatur.'
            ]);
         Activity::create([
            'activityName'      => 'Activité 4',
            'activityDesc' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit facilis hic tenetur sapiente aliquam. Minima quod a rem voluptas soluta commodi libero laudantium illo, exercitationem aspernatur blanditiis beatae saepe hic excepturi nihil doloribus rerum eum sequi molestias cupiditate illum odio aliquam ratione sint. Dolore, harum quisquam cupiditate doloribus eius ullam, id perspiciatis. Placeat necessitatibus architecto nulla maiores eos eligendi vitae vero. Libero officiis sit cupiditate ratione mollitia qui, ullam, accusamus sequi repellendus impedit cumque amet eos ab nesciunt nihil quod vitae odit a. Repellendus consequatur ea quos ab eaque. Quibusdam sed voluptate omnis quam, est dicta consectetur soluta sunt, recusandae praesentium cumque mollitia explicabo quo dignissimos a porro consequuntur delectus quia repellendus saepe, deserunt, voluptatum adipisci esse non facere. Officia explicabo, nihil dolorum nemo necessitatibus libero omnis, velit magni numquam alias! Sequi quisquam ex excepturi nobis, laudantium ut reiciendis. Perspiciatis voluptas provident itaque quis odio quam, commodi quidem nam voluptate eveniet, esse nisi adipisci totam deserunt illum voluptatem eaque. Facilis maxime quia error soluta aliquid quasi aspernatur, enim, tempora nobis necessitatibus ea nemo voluptate deleniti eius. Harum aliquid ab voluptate voluptatibus ipsam. Incidunt facere odio, alias nisi error, adipisci totam rerum, sequi fuga nobis culpa quos voluptates hic atque consequatur.'
            ]);
         Activity::create([
            'activityName'      => 'Activité 5',
            'activityDesc' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit facilis hic tenetur sapiente aliquam. Minima quod a rem voluptas soluta commodi libero laudantium illo, exercitationem aspernatur blanditiis beatae saepe hic excepturi nihil doloribus rerum eum sequi molestias cupiditate illum odio aliquam ratione sint. Dolore, harum quisquam cupiditate doloribus eius ullam, id perspiciatis. Placeat necessitatibus architecto nulla maiores eos eligendi vitae vero. Libero officiis sit cupiditate ratione mollitia qui, ullam, accusamus sequi repellendus impedit cumque amet eos ab nesciunt nihil quod vitae odit a. Repellendus consequatur ea quos ab eaque. Quibusdam sed voluptate omnis quam, est dicta consectetur soluta sunt, recusandae praesentium cumque mollitia explicabo quo dignissimos a porro consequuntur delectus quia repellendus saepe, deserunt, voluptatum adipisci esse non facere. Officia explicabo, nihil dolorum nemo necessitatibus libero omnis, velit magni numquam alias! Sequi quisquam ex excepturi nobis, laudantium ut reiciendis. Perspiciatis voluptas provident itaque quis odio quam, commodi quidem nam voluptate eveniet, esse nisi adipisci totam deserunt illum voluptatem eaque. Facilis maxime quia error soluta aliquid quasi aspernatur, enim, tempora nobis necessitatibus ea nemo voluptate deleniti eius. Harum aliquid ab voluptate voluptatibus ipsam. Incidunt facere odio, alias nisi error, adipisci totam rerum, sequi fuga nobis culpa quos voluptates hic atque consequatur.'
            ]);
         Activity::create([
            'activityName'      => 'Activité 6',
            'activityDesc' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit facilis hic tenetur sapiente aliquam. Minima quod a rem voluptas soluta commodi libero laudantium illo, exercitationem aspernatur blanditiis beatae saepe hic excepturi nihil doloribus rerum eum sequi molestias cupiditate illum odio aliquam ratione sint. Dolore, harum quisquam cupiditate doloribus eius ullam, id perspiciatis. Placeat necessitatibus architecto nulla maiores eos eligendi vitae vero. Libero officiis sit cupiditate ratione mollitia qui, ullam, accusamus sequi repellendus impedit cumque amet eos ab nesciunt nihil quod vitae odit a. Repellendus consequatur ea quos ab eaque. Quibusdam sed voluptate omnis quam, est dicta consectetur soluta sunt, recusandae praesentium cumque mollitia explicabo quo dignissimos a porro consequuntur delectus quia repellendus saepe, deserunt, voluptatum adipisci esse non facere. Officia explicabo, nihil dolorum nemo necessitatibus libero omnis, velit magni numquam alias! Sequi quisquam ex excepturi nobis, laudantium ut reiciendis. Perspiciatis voluptas provident itaque quis odio quam, commodi quidem nam voluptate eveniet, esse nisi adipisci totam deserunt illum voluptatem eaque. Facilis maxime quia error soluta aliquid quasi aspernatur, enim, tempora nobis necessitatibus ea nemo voluptate deleniti eius. Harum aliquid ab voluptate voluptatibus ipsam. Incidunt facere odio, alias nisi error, adipisci totam rerum, sequi fuga nobis culpa quos voluptates hic atque consequatur.'
            ]);
         Activity::create([
            'activityName'      => 'Activité 7',
            'activityDesc' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit facilis hic tenetur sapiente aliquam. Minima quod a rem voluptas soluta commodi libero laudantium illo, exercitationem aspernatur blanditiis beatae saepe hic excepturi nihil doloribus rerum eum sequi molestias cupiditate illum odio aliquam ratione sint. Dolore, harum quisquam cupiditate doloribus eius ullam, id perspiciatis. Placeat necessitatibus architecto nulla maiores eos eligendi vitae vero. Libero officiis sit cupiditate ratione mollitia qui, ullam, accusamus sequi repellendus impedit cumque amet eos ab nesciunt nihil quod vitae odit a. Repellendus consequatur ea quos ab eaque. Quibusdam sed voluptate omnis quam, est dicta consectetur soluta sunt, recusandae praesentium cumque mollitia explicabo quo dignissimos a porro consequuntur delectus quia repellendus saepe, deserunt, voluptatum adipisci esse non facere. Officia explicabo, nihil dolorum nemo necessitatibus libero omnis, velit magni numquam alias! Sequi quisquam ex excepturi nobis, laudantium ut reiciendis. Perspiciatis voluptas provident itaque quis odio quam, commodi quidem nam voluptate eveniet, esse nisi adipisci totam deserunt illum voluptatem eaque. Facilis maxime quia error soluta aliquid quasi aspernatur, enim, tempora nobis necessitatibus ea nemo voluptate deleniti eius. Harum aliquid ab voluptate voluptatibus ipsam. Incidunt facere odio, alias nisi error, adipisci totam rerum, sequi fuga nobis culpa quos voluptates hic atque consequatur.'
            ]);
         Activity::create([
            'activityName'      => 'Activité 8',
            'activityDesc' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit facilis hic tenetur sapiente aliquam. Minima quod a rem voluptas soluta commodi libero laudantium illo, exercitationem aspernatur blanditiis beatae saepe hic excepturi nihil doloribus rerum eum sequi molestias cupiditate illum odio aliquam ratione sint. Dolore, harum quisquam cupiditate doloribus eius ullam, id perspiciatis. Placeat necessitatibus architecto nulla maiores eos eligendi vitae vero. Libero officiis sit cupiditate ratione mollitia qui, ullam, accusamus sequi repellendus impedit cumque amet eos ab nesciunt nihil quod vitae odit a. Repellendus consequatur ea quos ab eaque. Quibusdam sed voluptate omnis quam, est dicta consectetur soluta sunt, recusandae praesentium cumque mollitia explicabo quo dignissimos a porro consequuntur delectus quia repellendus saepe, deserunt, voluptatum adipisci esse non facere. Officia explicabo, nihil dolorum nemo necessitatibus libero omnis, velit magni numquam alias! Sequi quisquam ex excepturi nobis, laudantium ut reiciendis. Perspiciatis voluptas provident itaque quis odio quam, commodi quidem nam voluptate eveniet, esse nisi adipisci totam deserunt illum voluptatem eaque. Facilis maxime quia error soluta aliquid quasi aspernatur, enim, tempora nobis necessitatibus ea nemo voluptate deleniti eius. Harum aliquid ab voluptate voluptatibus ipsam. Incidunt facere odio, alias nisi error, adipisci totam rerum, sequi fuga nobis culpa quos voluptates hic atque consequatur.'
            ]);
         Activity::create([
            'activityName'      => 'Activité 9',
            'activityDesc' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit facilis hic tenetur sapiente aliquam. Minima quod a rem voluptas soluta commodi libero laudantium illo, exercitationem aspernatur blanditiis beatae saepe hic excepturi nihil doloribus rerum eum sequi molestias cupiditate illum odio aliquam ratione sint. Dolore, harum quisquam cupiditate doloribus eius ullam, id perspiciatis. Placeat necessitatibus architecto nulla maiores eos eligendi vitae vero. Libero officiis sit cupiditate ratione mollitia qui, ullam, accusamus sequi repellendus impedit cumque amet eos ab nesciunt nihil quod vitae odit a. Repellendus consequatur ea quos ab eaque. Quibusdam sed voluptate omnis quam, est dicta consectetur soluta sunt, recusandae praesentium cumque mollitia explicabo quo dignissimos a porro consequuntur delectus quia repellendus saepe, deserunt, voluptatum adipisci esse non facere. Officia explicabo, nihil dolorum nemo necessitatibus libero omnis, velit magni numquam alias! Sequi quisquam ex excepturi nobis, laudantium ut reiciendis. Perspiciatis voluptas provident itaque quis odio quam, commodi quidem nam voluptate eveniet, esse nisi adipisci totam deserunt illum voluptatem eaque. Facilis maxime quia error soluta aliquid quasi aspernatur, enim, tempora nobis necessitatibus ea nemo voluptate deleniti eius. Harum aliquid ab voluptate voluptatibus ipsam. Incidunt facere odio, alias nisi error, adipisci totam rerum, sequi fuga nobis culpa quos voluptates hic atque consequatur.'
            ]);
         Activity::create([
            'activityName'      => 'Activité 10',
            'activityDesc' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit facilis hic tenetur sapiente aliquam. Minima quod a rem voluptas soluta commodi libero laudantium illo, exercitationem aspernatur blanditiis beatae saepe hic excepturi nihil doloribus rerum eum sequi molestias cupiditate illum odio aliquam ratione sint. Dolore, harum quisquam cupiditate doloribus eius ullam, id perspiciatis. Placeat necessitatibus architecto nulla maiores eos eligendi vitae vero. Libero officiis sit cupiditate ratione mollitia qui, ullam, accusamus sequi repellendus impedit cumque amet eos ab nesciunt nihil quod vitae odit a. Repellendus consequatur ea quos ab eaque. Quibusdam sed voluptate omnis quam, est dicta consectetur soluta sunt, recusandae praesentium cumque mollitia explicabo quo dignissimos a porro consequuntur delectus quia repellendus saepe, deserunt, voluptatum adipisci esse non facere. Officia explicabo, nihil dolorum nemo necessitatibus libero omnis, velit magni numquam alias! Sequi quisquam ex excepturi nobis, laudantium ut reiciendis. Perspiciatis voluptas provident itaque quis odio quam, commodi quidem nam voluptate eveniet, esse nisi adipisci totam deserunt illum voluptatem eaque. Facilis maxime quia error soluta aliquid quasi aspernatur, enim, tempora nobis necessitatibus ea nemo voluptate deleniti eius. Harum aliquid ab voluptate voluptatibus ipsam. Incidunt facere odio, alias nisi error, adipisci totam rerum, sequi fuga nobis culpa quos voluptates hic atque consequatur.'
            ]);
         Activity::create([
            'activityName'      => 'Activité 11',
            'activityDesc' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit facilis hic tenetur sapiente aliquam. Minima quod a rem voluptas soluta commodi libero laudantium illo, exercitationem aspernatur blanditiis beatae saepe hic excepturi nihil doloribus rerum eum sequi molestias cupiditate illum odio aliquam ratione sint. Dolore, harum quisquam cupiditate doloribus eius ullam, id perspiciatis. Placeat necessitatibus architecto nulla maiores eos eligendi vitae vero. Libero officiis sit cupiditate ratione mollitia qui, ullam, accusamus sequi repellendus impedit cumque amet eos ab nesciunt nihil quod vitae odit a. Repellendus consequatur ea quos ab eaque. Quibusdam sed voluptate omnis quam, est dicta consectetur soluta sunt, recusandae praesentium cumque mollitia explicabo quo dignissimos a porro consequuntur delectus quia repellendus saepe, deserunt, voluptatum adipisci esse non facere. Officia explicabo, nihil dolorum nemo necessitatibus libero omnis, velit magni numquam alias! Sequi quisquam ex excepturi nobis, laudantium ut reiciendis. Perspiciatis voluptas provident itaque quis odio quam, commodi quidem nam voluptate eveniet, esse nisi adipisci totam deserunt illum voluptatem eaque. Facilis maxime quia error soluta aliquid quasi aspernatur, enim, tempora nobis necessitatibus ea nemo voluptate deleniti eius. Harum aliquid ab voluptate voluptatibus ipsam. Incidunt facere odio, alias nisi error, adipisci totam rerum, sequi fuga nobis culpa quos voluptates hic atque consequatur.'
            ]);
         Activity::create([
            'activityName'      => 'Activité 12',
            'activityDesc' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit facilis hic tenetur sapiente aliquam. Minima quod a rem voluptas soluta commodi libero laudantium illo, exercitationem aspernatur blanditiis beatae saepe hic excepturi nihil doloribus rerum eum sequi molestias cupiditate illum odio aliquam ratione sint. Dolore, harum quisquam cupiditate doloribus eius ullam, id perspiciatis. Placeat necessitatibus architecto nulla maiores eos eligendi vitae vero. Libero officiis sit cupiditate ratione mollitia qui, ullam, accusamus sequi repellendus impedit cumque amet eos ab nesciunt nihil quod vitae odit a. Repellendus consequatur ea quos ab eaque. Quibusdam sed voluptate omnis quam, est dicta consectetur soluta sunt, recusandae praesentium cumque mollitia explicabo quo dignissimos a porro consequuntur delectus quia repellendus saepe, deserunt, voluptatum adipisci esse non facere. Officia explicabo, nihil dolorum nemo necessitatibus libero omnis, velit magni numquam alias! Sequi quisquam ex excepturi nobis, laudantium ut reiciendis. Perspiciatis voluptas provident itaque quis odio quam, commodi quidem nam voluptate eveniet, esse nisi adipisci totam deserunt illum voluptatem eaque. Facilis maxime quia error soluta aliquid quasi aspernatur, enim, tempora nobis necessitatibus ea nemo voluptate deleniti eius. Harum aliquid ab voluptate voluptatibus ipsam. Incidunt facere odio, alias nisi error, adipisci totam rerum, sequi fuga nobis culpa quos voluptates hic atque consequatur.'
            ]);
    }

}